version: '3'
services:

    ks-zookeeper:
        image: "confluentinc/cp-zookeeper:5.1.0"
        ports:
            - "12181:12181"
        environment:
            - ZOOKEEPER_CLIENT_PORT=12181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_SYNC_LIMIT=2

    kafka-broker1:
        image: "confluentinc/cp-kafka:5.1.0"
        depends_on:
            - ks-zookeeper
        ports:
            - "19092:19092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=ks-zookeeper:12181
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
            - KAFKA_LISTENERS=LISTENER_EXTERNAL://0.0.0.0:19092,LISTENER_INTERNAL://0.0.0.0:9092
            - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXTERNAL://localhost:19092,LISTENER_INTERNAL://kafka-broker1:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=100

    kafka-broker2:
        image: "confluentinc/cp-kafka:5.1.0"
        depends_on:
            - ks-zookeeper
        ports:
            - "29092:29092"
        environment:
            - KAFKA_BROKER_ID=2
            - KAFKA_ZOOKEEPER_CONNECT=ks-zookeeper:12181
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
            - KAFKA_LISTENERS=LISTENER_EXTERNAL://0.0.0.0:29092,LISTENER_INTERNAL://0.0.0.0:9092
            - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXTERNAL://localhost:29092,LISTENER_INTERNAL://kafka-broker2:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=100
